### ISSUE TITLE
mat_picmip and stream_memory not working.

### ISSUE THREAD

**Issue by sebxl** [deaFPS/apex#2]
The textures are the same when mat_picmip is set to 1,2,3 or 4. It doesnt work even when stream_memory is set to "0". Setting stream_memory to any other value besides "0" causes my game to look like this: https://imgur.com/a/iL7YS4k

**Comment by deaFPS** [comment]
those convars work together. so for high res textures you will need to put your picmip to 1 and stream_memory to 307200 (4gb).
your issue looks more like a driver issue tho

**Comment by sebxl** [comment]
Yea it actually was a driver issue. Thanks
